apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myapp-build-mono-template
parameters:
  - name: NAME
    description: The name of the build config
    required: true
  - name: GIT_REF
    description: The git reference to build from
    required: true
  - name: GIT_URI
    description: The URI of the git repository
    required: true
  - name: CONTEXT_DIR
    description: The context directory for the build
    value: "/"
    required: true
  - name: OUTPUT_NAME
    description: The name of the ImageStreamTag to output
    required: true
  - name: DOCKER_FILE_PATH
    description: specify the location of the Dockerfile in the source repository which OpenShift uses to execute a Docker build
    value: "Dockerfile"
  - name: REPOSITORY_URL
    description: specify the base url of remote repository where the images will be stored
    required: true
  - name: IMAGE_TAG
    description: image tag
    required: true
  - name: IMAGE_PUSH_SECRET
    description: push secret is required to pull or push image to the repository
    required: true

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
    spec:
      source:
        type: Git
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URI}
      runPolicy: SerialLatestOnly #enabled for iterative development
      output:
        to:
          kind: ImageStreamTag
          name: ${OUTPUT_NAME}  #<property>-<app>:<env>
      resources:
        limits:
          cpu: '2000m'
          memory: '2Gi'
        requests:
          cpu: '500m'
          memory: '512Mi'
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: ${DOCKER_FILE_PATH}