kind: "Template"
apiVersion: "v1"
metadata:
  name: secret-template
objects:
  - apiVersion: v1
    data:
      .dockerconfigjson: ${REPO_ACCESS_SECRET}
    kind: Secret
    metadata:
      name: property-image-store-secret
    type: kubernetes.io/dockerconfigjson
parameters:
  - name: REPO_ACCESS_SECRET
    description: Secret for accessing Docker registry
    required: true